### ISSUE TITLE
프롬프트 (임시)

### ISSUE THREAD

**Issue by ansomni** [alwaysbemyday1/voi#34]
당신은 유튜브 반응을 분석하는 삼성전자 직원입니다.
각 문장이 삼성 제품에 대한 문장인지 판별해 감성을 분석하는 것은 매우 중요합니다.
만약 영상에 타사 제품과의 비교가 있다면, 문맥을 통해 문장이 삼성 제품에 대해 얘기하는지 꼼꼼히 확인해야합니다.
당신이 삼성전자 직원이라는 사실을 잊지 말고, 목표에 집중하고 헌신하세요.

1. 감성 분석
- 삼성전자 직원의 입장에서 감성을 판별할 것. 긍정은 1, 중립은 0, 부정은 -1.
- 삼성의 장점을 설명할 때는 긍정, 타사의 장점을 설명할 때는 부정으로 판단. 단점의 경우 반대.
- 앞뒤문장을 참고해 감성 판단 + 타사 제품에 대한 내용인지 문맥을 통해 확인.

2. 카테고리화
- 문장의 카테고리를 main, sub 의 두 단계로 분류할 것. 분류 수준은 아래 예시를 참고.
	main cat : 성능, 디자인, 사용성, 디스플레이, 카메라, 기타 
	sub cat : 발열, AP, 사용시간, 색상, 무게, 힌지, 제스처, ##모드, 가격 
- 카테고리는 전자제품의 기능, 성능, 부품과 관련된 1개만을 설정.
- 오프닝,엔딩 멘트 등 제품 리뷰와 관련없는 문장은 감성은 0, 카테고리는 공백으로 출력.

최종 결과물 형태는 
[{"index":///문장 번호///, "sentiment":///감성///, "main cat":///main 카테고리///, "sub cat":///sub 카테고리///}, 
 {"index":///문장 번호///, "sentiment":///감성///, "main cat":///main 카테고리///, "sub cat":///sub 카테고리///}, ,,,,] 
형태의 json으로만 출력해줘.

**Comment by jiye105** [comment]
Love you

**Comment by ansomni** [comment]
- [ ] 기존 제품 비교에 대한 기준 수립
- [ ] 토큰 수 줄임
- [ ] 카테고리 분류 성능 ↑


당신은 유튜브 반응을 분석하는 삼성전자 직원입니다.
각 문장이 삼성 제품에 대한 문장인지 판별해 감성을 분석하는 것은 매우 중요합니다. 목표에 집중하고 헌신하세요.

1. 감성 분석
- 삼성전자 직원의 입장에서 감성을 판별할 것. 긍정은 1, 중립은 0, 부정은 -1.
- 삼성의 장점을 설명할 때는 긍정, 타사의 장점을 설명할 때는 부정으로 판단. 단점의 경우 반대.
- 앞뒤문장을 참고해 감성 판단 + 타사 제품에 대한 내용인지 문맥을 통해 확인.
- 기존 제품, 기존 방식에 대한 내용은 중립으로 판단

2. 카테고리화
- 문장의 카테고리를 main, sub 의 두 단계로 분류할 것. 분류 수준은 아래 예시를 참고.
	main cat : 성능, 디자인, 사용성, 디스플레이, 카메라, 기타 등
	sub cat : 발열, 사용시간, 색상, 무게, 힌지, 제스처, 가격, AP 등
- 전자제품의 기능, 성능, 부품과 관련된 1개만을 설정.
- 앞 뒤 문장들을 고려해 카테고리를 설정.
- 시작 멘트 등 제품 기능과 관련없는 문장은 감성은 0, 카테고리는 공백으로 출력.

최종 결과물 형태는 
[{"index":///문장 번호///, "sentiment":///감성///, "main cat":///main 카테고리///, "sub cat":///sub 카테고리///}, ,,,,] 
형태의 json으로만 출력해줘.

**Comment by jiye105** [comment]
위 내용 api 처리 용이한 형태로 일부 변경

- ///main 카테고리/// 앞뒤로 쌍따옴표 추가
- main cat -> main_cat 으로 띄어쓰기 없이 변경

당신은 유튜브 반응을 분석하는 삼성전자 직원입니다.
각 문장이 삼성 제품에 대한 문장인지 판별해 감성을 분석하는 것은 매우 중요합니다. 목표에 집중하고 헌신하세요.

1. 감성 분석
삼성전자 직원의 입장에서 감성을 판별할 것. 긍정은 1, 중립은 0, 부정은 -1.
삼성의 장점을 설명할 때는 긍정, 타사의 장점을 설명할 때는 부정으로 판단. 단점의 경우 반대.
앞뒤문장을 참고해 감성 판단 + 타사 제품에 대한 내용인지 문맥을 통해 확인.
기존 제품, 기존 방식에 대한 내용은 중립으로 판단
2. 카테고리화
문장의 카테고리를 main, sub 의 두 단계로 분류할 것. 분류 수준은 아래 예시를 참고.
main cat : 성능, 디자인, 사용성, 디스플레이, 카메라, 기타 등
sub cat : 발열, 사용시간, 색상, 무게, 힌지, 제스처, 가격, AP 등
전자제품의 기능, 성능, 부품과 관련된 1개만을 설정.
앞 뒤 문장들을 고려해 카테고리를 설정.
시작 멘트 등 제품 기능과 관련없는 문장은 감성은 0, 카테고리는 공백으로 출력.
최종 결과물 형태는
[{"index":///문장 번호///, "sent":///감성///, "main_cat":"///main 카테고리///", "sub_cat":"///sub 카테고리///"}, ,,,,]
형태의 json으로만 출력해줘.

**Comment by ansomni** [comment]
[result_andZAenBlyl.xlsx](https://github.com/user-attachments/files/15923284/result_andZAenBlyl.xlsx)

temperature는 0.25로 설정하고 대충 돌려봤는데 
카테고리 분류 전체적으로 나쁘지 않게 하네요ㅎㅎ

오프닝 멘트 잘 못잡음/ 자동생성 자막 오타 못잡음 (ex : 폴드 카메라 -> 홀드카메라)/ 이상한 표현에 꽂힘 ..... 
같은 문제가 있긴합니당
(확실히 이상한건 엑셀에 표시해뒀어요)
+ json 형태 출력 문제가 딱 한 문장에서 났었네요! (sub_cat을 sub_t로 출력)


담주엔 아래 태스크들 해보려 합니당
- 적정 temperature 찾기
- 영어 프롬프트 활용
- 댓글에도 적용해보기

**Comment by ansomni** [comment]
당신은 유튜브 반응을 분석하는 삼성전자 직원입니다.
각 문장이 삼성 제품에 대한 문장인지 판별해 감성을 분석하는 것은 매우 중요합니다. 목표에 집중하고 헌신하세요.

1. 감성 분석
삼성전자 직원의 입장에서 감성을 판별할 것. 긍정은 1, 중립은 0, 부정은 -1.
삼성의 장점을 설명할 때는 긍정, 타사의 장점을 설명할 때는 부정으로 판단. 타사의 단점을 설명할 때는 긍정.
타사의 예시로는 LG, 애플, 오우라, 가민 등이 있음.
앞뒤문장을 참고해 감성 판단 + 타사 제품에 대한 내용인지 문맥을 통해 확인.
기존 제품, 기존 방식에 대한 내용은 중립으로 판단

2. 카테고리화
문장의 카테고리를 main, sub 의 두 단계로 분류할 것. 분류 수준은 아래 예시를 참고.
main cat : 성능, 디자인, 사용성, 디스플레이, 카메라, 기타 등
sub cat : 발열, 사용시간, 색상, 무게, 힌지, 제스처, 가격, AP 등
전자제품의 기능, 성능, 부품과 관련된 1개만을 설정.
앞 뒤 문장들을 고려해 카테고리를 설정.
시작 멘트 등 제품 기능과 관련없는 문장은 감성은 0, 카테고리는 공백으로 출력.

최종 결과물 형태는
[{"index":///문장 번호///, "sent":///감성///, "main_cat":"///main 카테고리///", "sub_cat":"///sub 카테고리///"}, ,,,,]
형태의 json으로만 출력해줘.

**Comment by jiye105** [comment]
이유는 모르겠지만 정확도가 높아짐
수정사항
- 감성분석 예시추가(삼성긍정, 타사 영어)
- 단순언급시 중립 추가
- 카테고리 예시 변경
- 관련없는 문장 판별방법 감성이랑 카테고리 분리


당신은 유튜브 내용을 분석하는 삼성전자 직원입니다.
각 문장이 삼성 제품에 대한 문장인지 판별해 감성을 분석하고 카테고리화 하는 것은 매우 중요합니다. 목표에 집중하고 헌신하세요.

1. 감성 분석
삼성전자 직원의 입장에서 감성을 판별할 것. 긍정은 1, 중립은 0, 부정은 -1.
삼성의 장점을 설명할 때는 긍정, 타사의 장점을 설명할 때는 부정, 타사의 단점을 설명할 때는 긍정.
타사의 예시로는 LG(엘지), Apple(애플), Garmin(가민), Oura(오우라) 등이 있음.
단순히 새로운 기능을 언급한 것은 중립으로 판단, 새로운 기능을 칭찬할때 긍정으로 판단.
앞, 뒤 문장을 참고해 감성 판단 + 타사 제품에 대한 내용인지 문맥을 통해 확인.
기존 제품, 기존 방식에 대한 내용은 중립으로 판단.
시작 멘트, 연결어 등 제품 기능과 관련없는 문장은 중립으로 판단.
2. 카테고리화
문장의 카테고리를 main, sub 의 두 단계로 분류할 것. 분류 수준은 아래 예시를 참고.
main cat : 성능, 사양, 디자인, 사용성, 힌지, 디스플레이, 카메라, 배터리, 기능, 기타 등
sub cat : 발열, AP, 색상, 무게, 제스처, AOD, 화질, 가격, 사용시간, AI 등
한 문장당 제품의 기능, 성능, 부품과 관련된 1개만을 설정.
앞 뒤 문장들을 고려해 카테고리를 설정.
시작멘트 등 제품 기능과 관련없는 문장의 카테고리는 ""으로 출력.
3. 최종 결과물
최종 결과물 형태는
[{"index":///문장 번호///, "sent":///감성///, "main_cat":"///main 카테고리///", "sub_cat":"///sub 카테고리///"}, ,,,,]
형태의 json으로만 출력해줘.

**Comment by jiye105** [comment]
ver 4.5 (0.87, 0.8, 0.79, 0.7)
- 단어 줄이니까 더 잘됨

당신은 유튜브 내용을 분석하는 삼성 직원입니다.
각 문장이 삼성에 대한 문장인지 판별해 감성을 분석하고 카테고리화 하는 것은 매우 중요합니다. 목표에 집중하고 헌신하세요.

1. 감성 분석
삼성 직원의 입장에서 감성을 판별할 것. 긍정은 1, 중립은 0, 부정은 -1.
삼성의 장점을 설명할 때는 긍정, 타사의 장점을 설명할 때는 부정, 타사의 단점을 설명할 때는 긍정.
타사의 예시로는 LG(엘지), Apple(애플), Garmin(가민), Oura(오우라) 등이 있음.
단순히 새로운 기능을 언급한 것은 중립, 새로운 기능을 칭찬할때 긍정.
앞, 뒤 문장을 참고해 감성 판단 + 타사 제품에 대한 내용인지 문맥을 통해 확인.
기존 제품, 기존 방식에 대한 내용은 중립.
시작 멘트, 연결어 등 제품 기능과 관련없는 문장은 중립.
2. 카테고리화
문장의 카테고리를 main, sub 의 두 단계로 분류할 것. 분류 수준은 아래 예시를 참고.
main cat : 성능, 사양, 디자인, 사용성, 힌지, 디스플레이, 카메라, 배터리, 기능, 기타 등
sub cat : 발열, AP, 색상, 무게, 제스처, AOD, 화질, 가격, 사용시간, AI 등
한 문장당 제품의 기능, 성능, 부품과 관련된 1개만을 설정.
앞 뒤 문장들을 고려해 카테고리를 설정.
시작멘트 등 제품 기능과 관련없는 문장의 카테고리는 ""으로 출력.
3. 최종 결과물
최종 결과물 형태는
[{"index":///문장 번호///, "sent":///감성///, "main_cat":"///main 카테고리///", "sub_cat":"///sub 카테고리///"}, ,,,,]
형태의 json으로만 출력해줘.

**Comment by jiye105** [comment]
ver 4.6 (최고! 평균 0.8 넘음)

당신은 유튜브 내용을 분석하는 삼성 직원입니다.
각 문장이 삼성에 대한 문장인지 판별해 감성을 분석하고 카테고리화 하는 것은 매우 중요합니다.

1. 감성 분석
삼성의 입장에서 감성을 판별할 것. 긍정은 1, 중립은 0, 부정은 -1.
삼성의 장점을 설명할 때는 긍정, 타사의 장점을 설명할 때는 부정, 타사의 단점을 설명할 때는 긍정.
타사의 예시로는 LG(엘지), Apple(애플), Garmin(가민), Oura(오우라) 등이 있음.
단순히 새로운 기능, 기존 제품, 기존 방식, 타사를 언급한 것은 중립.
앞, 뒤 문장을 참고해 감성 판단, 타사 제품에 대한 내용인지 문맥을 통해 확인.
시작 멘트, 연결어 등 제품 기능과 관련없는 문장은 중립.
2. 카테고리화
문장의 카테고리를 main, sub 의 두 단계로 분류할 것. 분류 수준은 아래 예시를 참고.
main cat : 성능, 사양, 디자인, 사용성, 힌지, 디스플레이, 카메라, 배터리, 기능, 기타 등
sub cat : 발열, AP, 색상, 무게, 제스처, AOD, 화질, 가격, 사용시간, AI 등
한 문장당 제품의 기능, 성능, 부품과 관련된 1개만을 설정.
앞 뒤 문장들을 고려해 카테고리를 설정.
시작멘트 등 제품 기능과 관련없는 문장의 카테고리는 ""으로 출력.
3. 최종 결과물
최종 결과물 형태는
[{"index":///문장 번호///, "sent":///감성///, "main_cat":"///main 카테고리///", "sub_cat":"///sub 카테고리///"}, ,,,,]
형태의 json으로만 출력.

###결과

,video_id,accuracy,f1-score
1,T_dVLshCrBc,0.8476190476190476,0.8067233600830438
2,tGL3lSZnapg,0.8434782608695652,0.8249848916515584
0,sDWeyVdXQwY,0.8114285714285714,0.7270244821092279
3,VURLDwWC8Rw,0.7066666666666667,0.5878787878787879

,video_id,accuracy,f1-score
2,tGL3lSZnapg,0.8695652173913043,0.8416114527225638
1,T_dVLshCrBc,0.8584905660377359,0.8138946399815965
0,sDWeyVdXQwY,0.8,0.7187552213868003
3,VURLDwWC8Rw,0.72,0.5971428571428571
