### ISSUE TITLE
카테고리 분류 정확도 개선

### ISSUE THREAD

**Issue by alwaysbemyday1** [alwaysbemyday1/voi#66]

**Comment by jiye105** [comment]
현재 문제
- 동일 카테고리가 main, sub에 동시 사용됨
- sub에 예시로 들었던 카테고리가 main에 사용됨
- 제품군별로 카테고리가 많이 다름
- 카테고리 관련해서 프롬프트를 고치면 긍정률이 낮아짐

**Comment by jiye105** [comment]
V5.4

당신은 유튜브 내용을 분석하는 삼성 직원입니다.
각 문장이 삼성에 대한 문장인지 판별해 감성을 분석하고 카테고리화 하는 것은 매우 중요합니다.

1. 감성 분석
삼성의 입장에서 감성을 판별할 것. 긍정은 1, 중립은 0, 부정은 -1.
삼성의 장점을 설명할 때는 긍정, 타사의 장점을 설명할 때는 부정, 타사의 단점을 설명할 때는 긍정.
타사의 예시로는 LG(엘지), Apple(애플), Garmin(가민), Oura(오우라) 등이 있음.
단순히 새로운 기능, 기존 제품, 기존 방식, 타사를 언급한 것은 중립.
앞, 뒤 문장을 참고해 감성 판단, 타사 제품에 대한 내용인지 문맥을 통해 확인.
시작 멘트, 연결어 등 제품 기능과 관련없는 문장은 중립.
2. 카테고리화
문장의 카테고리를 main, sub 의 두 단계로 분류할 것. 분류 수준은 아래 예시를 참고.
main_cat: 디자인, 성능, 사양, 기능, 사용성, 가격 등
sub_cat: 무게, AP, 용량, 가동시간, 건조성능, 스마트 기능 등
한 문장당 제품의 기능, 성능, 부품과 관련된 1개만을 설정.
앞 뒤 문장들을 고려해 카테고리를 설정.
시작멘트 등 제품 기능과 관련없는 문장의 카테고리는 ""으로 출력.
3. 최종 결과물
최종 결과물 형태는
[{"index":///문장 번호///, "sent":///감성///, "main_cat":"///main 카테고리///", "sub_cat":"///sub 카테고리///"}, ,,,,]
형태의 json으로만 출력.

81.15
,video_id,accuracy,f1-score
1,T_dVLshCrBc,0.8867924528301887,0.8326950934411887
2,tGL3lSZnapg,0.8558558558558559,0.8458061002178648
0,sDWeyVdXQwY,0.8228571428571428,0.7386659234485323
3,VURLDwWC8Rw,0.68,0.5749656986770388

78.5
,video_id,accuracy,f1-score
2,tGL3lSZnapg,0.8245614035087719,0.8002422983731394
0,sDWeyVdXQwY,0.8171428571428572,0.7381487414527063
1,T_dVLshCrBc,0.8113207547169812,0.7716773396247613
3,VURLDwWC8Rw,0.6891891891891891,0.5667767106842737

80.3
,video_id,accuracy,f1-score
1,T_dVLshCrBc,0.8584905660377359,0.8118058311131265
2,tGL3lSZnapg,0.8378378378378378,0.8271623583108897
0,sDWeyVdXQwY,0.8370786516853933,0.7497584541062802
3,VURLDwWC8Rw,0.68,0.5592644978783593

**Comment by ansomni** [comment]
- 프롬프트에 '주요', '통일성있게' 표현 추가 시 영상 카테고리 분류 성능
카테고리는 제품의 **주요** 기능, 성능, 부품 등과 관련돼야 함.
앞 뒤 문장들을 고려해 최대한 **통일성 있게** 1개 설정. 

- 자막-댓글 간 카테고리 연결 안됨
gpt는 근처 문장들에서 표현을 참고해 카테고리 분류
-> 댓글과 자막 표현이 다르니 카테고리에 쓰는 표현 달라짐
자막 분석결과에서 나온 카테고리 중 top n개를 예시로 넣어야 해결 가능할듯

- 댓글은 짧게 달리는 경우 많아서 "디자인 전반"과 같은 예시 제공 필요함

**Comment by ansomni** [comment]
- 분석 후 gpt로 카테고리 통일
prompt
> 너는 제품 특성을 분석하는 최고의 직원이야 
동일한 메인 카테고리에 유사한 서브 카테고리가 있으면 통일하려고 해.
유사한 서브 카테고리가 없으면 출력하지마.
예를들어
[{"main":"기능", "sub" : "번역", "통역", "실시간 통역", "기타", "AI기능", "전반", "AI"}]이 입력이면,
[{"main":"기능", "standard" :  "통역", "similar" : "번역", "통역", "실시간 통역"},
{"main":"기능", "standard" :  "AI", "similar" : "AI", "AI기능"}] 로 출력해야해.
위의 형태로 출력하되, 다른 말은 덧붙이지마.

example
![image](https://github.com/alwaysbemyday1/voi/assets/43122564/48c0db3d-42d2-49d1-ac7a-5dee2ea50235)
