### ISSUE TITLE
Youtube list

### ISSUE THREAD

**Issue by jiye105** [alwaysbemyday1/voi#90]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/JIYE10~1.SHI/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/JIYE10~1.SHI/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

No. | 제목 | URL | 영상 등록일 | 유튜버 | search_key | 언어 | 센싱일 | 조회수 | 영상길이(s) | 담당
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
19 | Samsung Galaxy Watch   7  (44mm) - Brutally Honest Review -   Watch before you buy! | https://www.youtube.com/watch?v=hOXFTqmEOgY | 2024-07-24 | Chigz Tech Reviews | Watch7 | English | 2024-07-25 | 14143 | 1520 | 김희수
5 | 90만원에 육박하는데 돈값 할까?   갤럭시워치 울트라 짧은 사용기 (+워치7) | https://www.youtube.com/watch?v=zsw-aAUP7U8 | 2024-07-24 | ITSub잇섭 | 워치7 | Korean | 2024-07-25 | 342611 | 1007 | 김희수
4 | 갤럭시 신기능 써 보고 박수치는 중..   폴드 6로 제대로 보여드릴게요! (+기존 갤럭시 활용 팁까지) | https://www.youtube.com/watch?v=fJqH9UHkZ5w | 2024-07-24 | 테크몽 Techmong | 폴드6 | Korean | 2024-07-25 | 68275 | 861 | 김희수
28 | Galaxy Watch Ultra:   Battery Life BUSTED or BOSS? Real World Test Results | https://www.youtube.com/watch?v=hU4LefprhOM | 2024-07-24 | AppX | Watch Ultra | English | 2024-07-25 | 2939 | 679 | 김희수
6 | 인기 케이스 몽땅 드립니다! 갤럭시   z폴드6 &amp; 플립6 with 슈피겐 | https://www.youtube.com/watch?v=wbsOitInM24 | 2024-07-24 | 고니TV | 폴드6 | Korean | 2024-07-25 | 3813 | 583 | 김희수
13 | Samsung Galaxy Z   Flip6 review | https://www.youtube.com/watch?v=2GaS97uC77w | 2024-07-24 | GSMArena Official | Flip6 | English | 2024-07-25 | 2055 | 522 | 김희수
17 | Đánh giá Galaxy Watch   Ultra: NGON HƠN APPLE WATCH ULTRA? | https://www.youtube.com/watch?v=uiiA1ycJaYA | 2024-07-24 | Admin Kha | Watch Ultra | Vietnamese | 2024-07-25 | 325 | 481 | 김희수
20 | [내돈내산] 갤럭시워치울트라 밴드   3종(마린밴드, 픽폼밴드, 트레일밴드) 뭐살지 추천해드림!    &amp; 갤럭시링 언박싱 포함! \| 사부작사부작 38편 | https://www.youtube.com/watch?v=C3cxwaoObXk | 2024-07-24 | 인태크 INTAECH | 갤럭시워치울트라 | Korean | 2024-07-25 | 2072 | 423 | 김희수
1 | Crafted Black Samsung   Galaxy Z Fold 6 Unboxing (Exclusive Color) | https://www.youtube.com/watch?v=rnOFYT3-ogs | 2024-07-24 | Danny Winget | Galaxy Fold6 | English | 2024-07-25 | 3423 | 58 | 김희수
2 | 디즈니 덕후라면 환장할 Z   플립6  수트 케이스ㅋㅋㅋㅋ | https://www.youtube.com/watch?v=NHR8yoh3G0E | 2024-07-24 | 오목교 전자상가 | 플립6 | Korean | 2024-07-25 | 1204 | 38 | 김희수
24 | This Foldable SMASHES   the Z Fold 6 \| Vivo X Fold 3 Pro Review | https://www.youtube.com/watch?v=RQd5mJBGpug | 2024-07-24 | Tech Spurt | Fold6 | English | 2024-07-25 | 23486 | 1182 | 신지예
9 | Switching to the   Samsung Galaxy Z Fold 6: My Verdict! | https://www.youtube.com/watch?v=sOQMKQVHwIY | 2024-07-24 | The Tech Chap | Fold6 | English | 2024-07-25 | 14947 | 944 | 신지예
16 | &quot;안 하면   손해!&quot; Z플립6 꼭 알아야 되는 놀라운 활용법 13가지 \| 커버화면 설정, 필수 설정, AI, 통역 기능 등등 총정리 | https://www.youtube.com/watch?v=60Jag56K7mA | 2024-07-24 | 인스펙팅룸 InspectingRoom | 플립6 | Korean | 2024-07-25 | 1387 | 839 | 신지예
18 | Samsung Galaxy Z Flip   6 One Week Later! | https://www.youtube.com/watch?v=QYLiG_YhgX0 | 2024-07-24 | The Everyday Dad | Flip6 | English | 2024-07-25 | 5466 | 639 | 신지예
23 | Galaxy Z Flip 6   Review: AI and Upgrades Stained by a High Price | https://www.youtube.com/watch?v=xQ0hJS41MdQ | 2024-07-24 | CNET | Flip6 | English | 2024-07-25 | 6961 | 557 | 신지예
8 | Samsung Ring Review:   Real Day In The Life! | https://www.youtube.com/watch?v=JDHaAwiEJmI | 2024-07-24 | NothingButTech | Galaxy Ring | English | 2024-07-25 | 3578 | 519 | 신지예
22 | Samsung Galaxy Z Fold   6 is a great phone that’s out of ideas | https://www.youtube.com/watch?v=tmQztSegEFc | 2024-07-24 | GregglesTV | Fold6 | English | 2024-07-25 | 574 | 443 | 신지예
10 | 효과가 미쳤는데요?   갤럭시Z폴드6 보호필름은 정품 AR보호필름으로 붙이세요. | https://www.youtube.com/watch?v=iAirdB9Bd9U | 2024-07-24 | 더신자 TheSINZA | 폴드6 | Korean | 2024-07-25 | 4423 | 258 | 신지예
7 | Galaxy Buds3 Pro -   Active Noise Cancelling On a Whole Other Level! #samsung #GalaxyBuds3Pro | https://www.youtube.com/watch?v=zY1HSHGDSSA | 2024-07-24 | Jimmy is Promo | Buds3 | English | 2024-07-25 | 1112 | 57 | 신지예
14 | 1 DEALBREAKER!   Samsung Galaxy Buds 3 Review | https://www.youtube.com/watch?v=fikF_p6oiYU | 2024-07-24 | DHRME | Galaxy Buds | English | 2024-07-25 | 1041 | 1075 | 안소민
3 | 아재폰이라고 그만 놀려도 될듯;;   이번에 진짜 맘에 드는 Z폴드6 좋은점6 아쉬운점6 (일주일 사용후기) | https://www.youtube.com/watch?v=n_z1uIoBRRE | 2024-07-24 | 주연 ZUYONI | 폴드6 | Korean | 2024-07-25 | 67138 | 927 | 안소민
21 | 오히려 너프된 배터리타임? 갤럭시   Z폴드6 2주간 실사용하면서 느낀 장단점 후기 | https://www.youtube.com/watch?v=XjEHwN32f10 | 2024-07-24 | KEVIN 케빈 - IT리뷰 | 폴드6 | Korean | 2024-07-25 | 5850 | 716 | 안소민
11 | 삼성 갤럭시Z폴드6: 두껍고 무거웠던   Z폴드 시리즈, 다이어트하니 잘 생겨졌다? 폴더블로 만나는 AI 경험 \| #Review | https://www.youtube.com/watch?v=OUq40XYwfoc | 2024-07-24 | CNET Korea | 폴드6 | Korean | 2024-07-25 | 2061 | 626 | 안소민
25 | 갤럭시 Z폴드6 핵심 설정 및 기능   10가지! 대화면 120% 활용 하자 | https://www.youtube.com/watch?v=JOo8BMWO55E | 2024-07-24 | 꿀단지PD | 폴드6 | Korean | 2024-07-25 | 5079 | 532 | 안소민
27 | Galaxy watch   Ultra \| Why Samsung Went Too Far With This | https://www.youtube.com/watch?v=67vSd5SAh0k | 2024-07-24 | Ivan Kam | Watch Ultra | English | 2024-07-25 | 3470 | 510 | 안소민
15 | 갤럭시 버즈3 프로 성능 불량도 문제   있나? 🤔 11개 측정 편차 분석 | https://www.youtube.com/watch?v=jUlwcdEFCkc | 2024-07-24 | 아레지나 테크리뷰 | 버즈3 | Korean | 2024-07-25 | 14835 | 425 | 안소민
12 | Samsung Galaxy Z   Flip6 - The Selfie and Vlogging Phone | https://www.youtube.com/watch?v=Un4DmlOWzqU | 2024-07-24 | Daniel Sin | Flip6 | English | 2024-07-25 | 229 | 257 | 안소민
26 | What Features are on   the Samsung Galaxy Buds 3 Pro? | https://www.youtube.com/watch?v=iM_4lIhX5UQ | 2024-07-24 | This is Tech Today | Galaxy Buds | English | 2024-07-25 | 969 | 45 | 안소민

</body>

</html>

**Comment by jiye105** [comment]
- [ ] @jiye105 
- [ ] @ansomni 
- [ ] @heesoo-k 
- [ ] @alwaysbemyday1 

git pull, read above, find your name and get it done(mean running time is quite similar, 
and it is sorted in alphabetical order of your name)

**Comment by jiye105** [comment]
videos = ['///리스트/////']
for video_url in videos:

    if len(video_url.split('v=')) > 1:
        video_id = video_url.split('v=')[1][:11]
    else:
        video_id = video_url
        
    info_df, caption_df, comment_df = youtube_analysis.analyze_video(video_id)
    info_df.to_csv(f"..\\data\\results\\info_csv_{video_id}.csv", encoding="utf-8-sig")
    caption_df.to_csv(f"..\\data\\results\\caption_analysis_{video_id}.csv", encoding='utf-8-sig')
    comment_df.to_csv(f"..\\data\\results\\comment_analysis_{video_id}.csv", encoding='utf-8-sig')

**Comment by jiye105** [comment]
videos = ['']
  for video_url in videos:
  
      if len(video_url.split('v=')) > 1:
          video_id = video_url.split('v=')[1][:11]
      else:
          video_id = video_url
          
      info_df, caption_df, comment_df = youtube_analysis.analyze_video(video_id)
      info_df.to_csv(f"..\\data\\results\\info_csv_{video_id}.csv", encoding="utf-8-sig")
      caption_df.to_csv(f"..\\data\\results\\caption_analysis_{video_id}.csv", encoding='utf-8-sig')
      comment_df.to_csv(f"..\\data\\results\\comment_analysis_{video_id}.csv", encoding='utf-8-sig')

**Comment by ansomni** [comment]
caption_df = pd.DataFrame(youtube_analysis.analyze_caption(video_id))
caption_df.to_csv(f"..\\data\\results\\caption_analysis_{video_id}.csv", encoding='utf-8-sig')

**Comment by jiye105** [comment]
[info_csv_iAirdB9Bd9U.csv](https://github.com/user-attachments/files/16368973/info_csv_iAirdB9Bd9U.csv)
[caption_analysis_zY1HSHGDSSA.csv](https://github.com/user-attachments/files/16368974/caption_analysis_zY1HSHGDSSA.csv)
[info_csv_zY1HSHGDSSA.csv](https://github.com/user-attachments/files/16368975/info_csv_zY1HSHGDSSA.csv)
[caption_analysis_60Jag56K7mA.csv](https://github.com/user-attachments/files/16368976/caption_analysis_60Jag56K7mA.csv)
[info_csv_60Jag56K7mA.csv](https://github.com/user-attachments/files/16368977/info_csv_60Jag56K7mA.csv)
[caption_analysis_iAirdB9Bd9U.csv](https://github.com/user-attachments/files/16368978/caption_analysis_iAirdB9Bd9U.csv)

**Comment by ansomni** [comment]
[caption_analysis_JOo8BMWO55E.csv](https://github.com/user-attachments/files/16369112/caption_analysis_JOo8BMWO55E.csv)
[caption_analysis_OUq40XYwfoc.csv](https://github.com/user-attachments/files/16369113/caption_analysis_OUq40XYwfoc.csv)
[caption_analysis_XjEHwN32f10',.csv](https://github.com/user-attachments/files/16369115/caption_analysis_XjEHwN32f10.csv)
[caption_analysis_n_z1uIoBRRE.csv](https://github.com/user-attachments/files/16369116/caption_analysis_n_z1uIoBRRE.csv)
[caption_analysis_jUlwcdEFCkc.csv](https://github.com/user-attachments/files/16369118/caption_analysis_jUlwcdEFCkc.csv)
[info_csv_JOo8BMWO55E.csv](https://github.com/user-attachments/files/16369122/info_csv_JOo8BMWO55E.csv)
[info_csv_jUlwcdEFCkc.csv](https://github.com/user-attachments/files/16369123/info_csv_jUlwcdEFCkc.csv)
[info_csv_n_z1uIoBRRE.csv](https://github.com/user-attachments/files/16369124/info_csv_n_z1uIoBRRE.csv)
[info_csv_OUq40XYwfoc.csv](https://github.com/user-attachments/files/16369125/info_csv_OUq40XYwfoc.csv)

**Comment by heesoo-k** [comment]
[info_csv_NHR8yoh3G0E.csv](https://github.com/user-attachments/files/16369151/info_csv_NHR8yoh3G0E.csv)
[caption_analysis_NHR8yoh3G0E.csv](https://github.com/user-attachments/files/16369152/caption_analysis_NHR8yoh3G0E.csv)
[info_csv_C3cxwaoObXk.csv](https://github.com/user-attachments/files/16369153/info_csv_C3cxwaoObXk.csv)
[caption_analysis_C3cxwaoObXk.csv](https://github.com/user-attachments/files/16369154/caption_analysis_C3cxwaoObXk.csv)
[info_csv_wbsOitInM24.csv](https://github.com/user-attachments/files/16369155/info_csv_wbsOitInM24.csv)
[caption_analysis_wbsOitInM24.csv](https://github.com/user-attachments/files/16369156/caption_analysis_wbsOitInM24.csv)
[info_csv_fJqH9UHkZ5w.csv](https://github.com/user-attachments/files/16369157/info_csv_fJqH9UHkZ5w.csv)
[caption_analysis_fJqH9UHkZ5w.csv](https://github.com/user-attachments/files/16369158/caption_analysis_fJqH9UHkZ5w.csv)
[info_csv_zsw-aAUP7U8.csv](https://github.com/user-attachments/files/16369159/info_csv_zsw-aAUP7U8.csv)
[caption_analysis_zsw-aAUP7U8.csv](https://github.com/user-attachments/files/16369160/caption_analysis_zsw-aAUP7U8.csv)

**Comment by jiye105** [comment]
[caption_analysis_6rNXweeiVUQ.csv](https://github.com/user-attachments/files/16372807/caption_analysis_6rNXweeiVUQ.csv)
