### ISSUE TITLE
Youtube list_240726

### ISSUE THREAD

**Issue by heesoo-k** [alwaysbemyday1/voi#97]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/heesoo.kim/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/heesoo.kim/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

No. | 제목 | URL | 영상 등록일 | 유튜버 | search_key | 언어 | 센싱일 | 조회수 | 영상길이(s) |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 핑크~?! #주저씨 #주연 #z폴드6 | https://www.youtube.com/watch?v=sNDhG5dhpH8 | 2024-07-25 | 주연 ZUYONI | 폴드6 | Korean | 2024-07-26 | 7590 | 24 | 김희수
2 | 곧 OneUI7 베타가 진행됩니다.   갤럭시S24, 폴드6 등부터 지원할 OneUI7 디자인 개편, 새로운 기능 등 루머 간단 정리 | https://www.youtube.com/watch?v=pjBxTKO_P9E | 2024-07-25 | KEVIN 케빈 - IT리뷰 | 폴드6 | Korean | 2024-07-26 | 12791 | 280 | 김희수
3 | Samsung Galaxy Buds 3   Pro colors and price | https://www.youtube.com/watch?v=9Nu8we1lrB0 | 2024-07-25 | This is Tech Today | Galaxy Buds | English | 2024-07-26 | 1693 | 14 | 김희수
4 | Samsung Galaxy Ring   Looks Impressive! | https://www.youtube.com/watch?v=Gsijt7-Vq5s | 2024-07-25 | Chigz Tech Reviews | Galaxy Ring | English | 2024-07-26 | 171 | 57 | 김희수
5 | Galaxy Watch 7   Review: This Feels Different. | https://www.youtube.com/watch?v=7noaPsX3bZI | 2024-07-25 | Thao | Galaxy Watch7 | English | 2024-07-26 | 27044 | 500 | 김희수
6 | Ich verstehe es   nicht... - Samsung Galaxy Z Fold 6 Review (Deutsch) \| SwagTab | https://www.youtube.com/watch?v=XKDRscRrdgs | 2024-07-25 | SwagTab | Fold6 | German | 2024-07-26 | 9794 | 862 | 김희수
7 | (우주 최강 귀여움) 갤럭시 Z플립6   춘식이 &amp; 키스해링 수트 케이스! | https://www.youtube.com/watch?v=y8jL4MW9wLU | 2024-07-25 | 꿀단지PD | 플립6 | Korean | 2024-07-26 | 745 | 47 | 김희수
8 | 갤럭시 워치7 샀는데 이거 안쓰면   후회합니다.. 삼성도 알려주지 않은 필수 초기설정 및 꿀팁 16가지 | https://www.youtube.com/watch?v=d5CID4fBFTc | 2024-07-25 | 고니TV | 워치7 | Korean | 2024-07-26 | 9625 | 883 | 김희수
9 | Z플립6 커버 화면 설정하는 꿀팁   (기능, 잠금화면, 설정, 성능) | https://www.youtube.com/watch?v=gmKOfbZJ-Fc | 2024-07-25 | 아정당 | 플립6 | English | 2024-07-26 | 2407 | 52 | 김희수
10 | Galaxy Z Fold 6 I   Removed the Factory Installed Screen Protector: What Now!? | https://www.youtube.com/watch?v=ax00dmj9puk | 2024-07-25 | GregglesTV | Fold6 | English | 2024-07-26 | 2080 | 206 | 김희수
11 | Samsung Galaxy Watch   Ultra and 7 Review: So Close to Being Truly Ultra | https://www.youtube.com/watch?v=KREwxYlzH48 | 2024-07-25 | CNET | Watch Ultra | English | 2024-07-26 | 12659 | 641 | 김희수
12 | Samsung Galaxy Z Flip   6 - &quot;Real Review&quot; | https://www.youtube.com/watch?v=AdJGabiljEI | 2024-07-25 | Flossy Carter | Flip6 | English | 2024-07-26 | 43196 | 4336 | 김희수
13 | 48시간 안에 꼭 해야 하는 버즈3   초기 불량 테스트! (버즈3 소음, 리뷰, 불량 확인) | https://www.youtube.com/watch?v=lc30rlsX2vU | 2024-07-25 | 아정당 | 버즈3 | Korean | 2024-07-26 | 3744 | 40 | 김희수
14 | 버즈3 시리즈 판매 중단 중.. 판매   시작되면 살만 할까? 8종 통화품질 비교 녹음본 공개 \| (링, 워치울트라 하루 사용기 포함) 사부작사부작 39편 | https://www.youtube.com/watch?v=LL-GGF_dgOU | 2024-07-25 | 인태크 INTAECH | 워치울트라 | Korean | 2024-07-26 | 504 | 783 | 김희수
15 | Samsung Galaxy Z Fold   6 fast charging test | https://www.youtube.com/watch?v=0LtP7HLhXAY | 2024-07-25 | Phandroid | Fold6 | English | 2024-07-26 | 77 | 40 | 김희수
16 | Unboxing the Samsung   Galaxy Watch Ultra #smartwatch | https://www.youtube.com/watch?v=p2unx9EYyGA | 2024-07-25 | Sypnotix | Galaxy Watch Ultra | English | 2024-07-26 | 430 | 60 | 안소민
17 | Samsung Galaxy Ring   Titanium Black Unboxing &amp; First Impressions! | https://www.youtube.com/watch?v=DX5RlNmCEGU | 2024-07-25 | MTG Productions | Galaxy Ring | English | 2024-07-26 | 84 | 621 | 안소민
18 | Samsung Galaxy Z Fold   6 VS OnePlus Open! | https://www.youtube.com/watch?v=UpKuhUSXia0 | 2024-07-25 | J. Williams | Fold6 | English | 2024-07-26 | 6486 | 2413 | 안소민
19 | [구독자이벤트]갤럭시Z플립6 케이스   이거 사세요 역대급으로 가볍고 얇은데 튼튼함😆 | https://www.youtube.com/watch?v=s80DGr6gKr0 | 2024-07-25 | 심플 Simple | 플립6 | Korean | 2024-07-26 | 150 | 216 | 안소민
20 | Z플립6, 폴드6 전 색상 실물   1위는? \| 삼성닷컴 단독 색상까지! 비교추천 순위 리뷰 (실버 쉐도우, 옐로우, 민트, 블루,핑크, 네이비, 화이트, 피치, 크래프티드   블랙) | https://www.youtube.com/watch?v=6naVjiwjmUY | 2024-07-25 | 아정당 | 폴드6 | Korean | 2024-07-26 | 2638 | 999 | 안소민
21 | Unboxing the Samsung   Galaxy Fold6 #smartphone | https://www.youtube.com/watch?v=7qw_raJUCfQ | 2024-07-25 | Sypnotix | Fold6 | English | 2024-07-26 | 437 | 56 | 안소민
22 | Samsung Galaxy Watch   Ultra vs Apple Watch 9: Animation Comparison | https://www.youtube.com/watch?v=71m5UOLgO98 | 2024-07-25 | Velian Speaks Tech | Watch Ultra | English | 2024-07-26 | 345 | 228 | 안소민
23 | Galaxy Z Fold6 Case   Review - My Experience So Far: One Improved, One is Awesome | https://www.youtube.com/watch?v=lJxCNf3i5nk | 2024-07-25 | Jimmy is Promo | Galaxy Fold6 | English | 2024-07-26 | 2182 | 717 | 안소민
24 | 애플도 안바꾸잖아..완성형 삼성   갤럭시워치7 개봉기 | https://www.youtube.com/watch?v=2INQJy4tCnY | 2024-07-25 | 리더유 | 워치7 | Korean | 2024-07-26 | 900 | 38 | 안소민
25 | 갤럭시 Z 폴드 6 사용 후기 : 지금   갖고 있는 스마트폰이 이와 같은 일을 할 수 있나요? | https://www.youtube.com/watch?v=mtdhzxmx7nI | 2024-07-25 | postiVIEW 포스티뷰 | 폴드6 | Korean | 2024-07-26 | 90 | 607 | 안소민
26 | 삼성에서 홍보 안 하는 갤럭시 꿀기능   소개합니다! (플립6, 폴드6, S시리즈, 갤럭시AI) | https://www.youtube.com/watch?v=7Gv7EV5qWRU | 2024-07-25 | 아정당 | 폴드6 | English | 2024-07-26 | 4519 | 38 | 안소민
27 | Samsung Galaxy Ring   Unboxing | https://www.youtube.com/watch?v=Nb9rIC3mOvs | 2024-07-25 | SuperSaf | Galaxy Ring |   | 2024-07-26 | 2357 | 60 | 안소민
28 | Galaxy Z Flip6:   It&#39;s AWESOME! \| Review - The One To Get! | https://www.youtube.com/watch?v=bCK8wM_i3h8 | 2024-07-25 | Mark's Tech | Flip6 | English | 2024-07-26 | 851 | 579 | 안소민
29 | Galaxy Buds3 Pro vs   AirPods Pro - Tested &amp; Compared! | https://www.youtube.com/watch?v=RJWYpW8w_R8 | 2024-07-25 | Mike O'Brien | Buds3 | English | 2024-07-26 | 9415 | 1138 | 안소민

</body>

</html>

**Comment by ansomni** [comment]
[info_csv_s80DGr6gKr0.csv](https://github.com/user-attachments/files/16385313/info_csv_s80DGr6gKr0.csv)
[caption_analysis_s80DGr6gKr0.csv](https://github.com/user-attachments/files/16385314/caption_analysis_s80DGr6gKr0.csv)
[info_csv_mtdhzxmx7nI.csv](https://github.com/user-attachments/files/16385309/info_csv_mtdhzxmx7nI.csv)
[caption_analysis_mtdhzxmx7nI.csv](https://github.com/user-attachments/files/16385310/caption_analysis_mtdhzxmx7nI.csv)
[info_csv_6naVjiwjmUY.csv](https://github.com/user-attachments/files/16385311/info_csv_6naVjiwjmUY.csv)
[caption_analysis_6naVjiwjmUY.csv](https://github.com/user-attachments/files/16385312/caption_analysis_6naVjiwjmUY.csv)

**Comment by heesoo-k** [comment]
[info_csv_gmKOfbZJ-Fc.csv](https://github.com/user-attachments/files/16385372/info_csv_gmKOfbZJ-Fc.csv)
[info_csv_LL-GGF_dgOU.csv](https://github.com/user-attachments/files/16385373/info_csv_LL-GGF_dgOU.csv)
[info_csv_d5CID4fBFTc.csv](https://github.com/user-attachments/files/16385374/info_csv_d5CID4fBFTc.csv)
[info_csv_pjBxTKO_P9E.csv](https://github.com/user-attachments/files/16385375/info_csv_pjBxTKO_P9E.csv)
[caption_analysis_sNDhG5dhpH8.csv](https://github.com/user-attachments/files/16385398/caption_analysis_sNDhG5dhpH8.csv)
[caption_analysis_y8jL4MW9wLU.csv](https://github.com/user-attachments/files/16385379/caption_analysis_y8jL4MW9wLU.csv)
[caption_analysis_lc30rlsX2vU.csv](https://github.com/user-attachments/files/16385380/caption_analysis_lc30rlsX2vU.csv)
[caption_analysis_gmKOfbZJ-Fc.csv](https://github.com/user-attachments/files/16385381/caption_analysis_gmKOfbZJ-Fc.csv)
[caption_analysis_LL-GGF_dgOU.csv](https://github.com/user-attachments/files/16385382/caption_analysis_LL-GGF_dgOU.csv)
[caption_analysis_d5CID4fBFTc.csv](https://github.com/user-attachments/files/16385383/caption_analysis_d5CID4fBFTc.csv)
[caption_analysis_pjBxTKO_P9E.csv](https://github.com/user-attachments/files/16385384/caption_analysis_pjBxTKO_P9E.csv)

**Comment by heesoo-k** [comment]
video_list = ["pjBxTKO_P9E", "d5CID4fBFTc", "LL-GGF_dgOU", "gmKOfbZJ-Fc", "lc30rlsX2vU", "y8jL4MW9wLU"]

**Comment by jiye105** [comment]
[caption_analysis_lc30rlsX2vU.csv](https://github.com/user-attachments/files/16385570/caption_analysis_lc30rlsX2vU.csv)
[info_csv_gmKOfbZJ-Fc.csv](https://github.com/user-attachments/files/16385572/info_csv_gmKOfbZJ-Fc.csv)
[caption_analysis_gmKOfbZJ-Fc.csv](https://github.com/user-attachments/files/16385574/caption_analysis_gmKOfbZJ-Fc.csv)
[info_csv_d5CID4fBFTc.csv](https://github.com/user-attachments/files/16385576/info_csv_d5CID4fBFTc.csv)
[caption_analysis_d5CID4fBFTc.csv](https://github.com/user-attachments/files/16385577/caption_analysis_d5CID4fBFTc.csv)
[info_csv_y8jL4MW9wLU.csv](https://github.com/user-attachments/files/16385578/info_csv_y8jL4MW9wLU.csv)
[caption_analysis_y8jL4MW9wLU.csv](https://github.com/user-attachments/files/16385579/caption_analysis_y8jL4MW9wLU.csv)
[info_csv_pjBxTKO_P9E.csv](https://github.com/user-attachments/files/16385580/info_csv_pjBxTKO_P9E.csv)
[caption_analysis_pjBxTKO_P9E.csv](https://github.com/user-attachments/files/16385581/caption_analysis_pjBxTKO_P9E.csv)
[info_csv_LL-GGF_dgOU.csv](https://github.com/user-attachments/files/16385582/info_csv_LL-GGF_dgOU.csv)
[caption_analysis_LL-GGF_dgOU.csv](https://github.com/user-attachments/files/16385584/caption_analysis_LL-GGF_dgOU.csv)
[info_csv_lc30rlsX2vU.csv](https://github.com/user-attachments/files/16385586/info_csv_lc30rlsX2vU.csv)

**Comment by jiye105** [comment]
[caption_analysis_sNDhG5dhpH8.csv](https://github.com/user-attachments/files/16385691/caption_analysis_sNDhG5dhpH8.csv)
[info_csv_sNDhG5dhpH8.csv](https://github.com/user-attachments/files/16385692/info_csv_sNDhG5dhpH8.csv)

**Comment by ansomni** [comment]
[info_csv_7noaPsX3bZI.csv](https://github.com/user-attachments/files/16385838/info_csv_7noaPsX3bZI.csv)
[caption_analysis_7noaPsX3bZI.csv](https://github.com/user-attachments/files/16385839/caption_analysis_7noaPsX3bZI.csv)

이제 영어도됩니다!
